package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"upwind-cli/internal/openapi"
)

var requiredSpecVersions = []string{"v1", "v2"}

func main() {
	var specDir string
	var outputPath string

	flag.StringVar(&specDir, "spec-dir", "", "Directory containing the upstream OpenAPI YAML files")
	flag.StringVar(&outputPath, "out", "", "Path to write the generated Go source")
	flag.Parse()

	if strings.TrimSpace(specDir) == "" {
		exitf("missing -spec-dir")
	}
	if strings.TrimSpace(outputPath) == "" {
		exitf("missing -out")
	}

	catalog, err := loadCatalog(specDir)
	if err != nil {
		exitf("%v", err)
	}

	source, err := renderCatalogSource(catalog)
	if err != nil {
		exitf("%v", err)
	}

	formatted, err := format.Source(source)
	if err != nil {
		exitf("format generated source: %v", err)
	}

	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		exitf("write generated source: %v", err)
	}
}

func loadCatalog(specDir string) (openapi.Catalog, error) {
	specFiles, err := discoverSpecFiles(specDir)
	if err != nil {
		return openapi.Catalog{}, err
	}
	if len(specFiles) == 0 {
		return openapi.Catalog{}, errors.New("no spec files found")
	}

	versions := map[string]openapi.VersionGroup{}
	versionFiles := map[string]string{}
	for _, specFile := range specFiles {
		contents, err := os.ReadFile(specFile)
		if err != nil {
			return openapi.Catalog{}, fmt.Errorf("read spec %s: %w", specFile, err)
		}

		version, err := detectVersion(contents)
		if err != nil {
			return openapi.Catalog{}, fmt.Errorf("detect version for %s: %w", specFile, err)
		}

		group, err := openapi.ParseVersion(version, contents)
		if err != nil {
			return openapi.Catalog{}, fmt.Errorf("parse %s from %s: %w", version, specFile, err)
		}

		if existingFile, ok := versionFiles[version]; ok {
			return openapi.Catalog{}, fmt.Errorf("duplicate %s spec files: %s and %s", version, existingFile, specFile)
		}

		versionFiles[version] = specFile
		versions[version] = group
	}

	missingVersions := make([]string, 0, len(requiredSpecVersions))
	for _, version := range requiredSpecVersions {
		if _, ok := versions[version]; !ok {
			missingVersions = append(missingVersions, version)
		}
	}
	if len(missingVersions) > 0 {
		return openapi.Catalog{}, fmt.Errorf("missing required spec versions: %s", strings.Join(missingVersions, ", "))
	}

	ordered := slices.Clone(requiredSpecVersions)

	result := openapi.Catalog{
		Versions: make([]openapi.VersionGroup, 0, len(ordered)),
	}
	for _, version := range ordered {
		result.Versions = append(result.Versions, versions[version])
	}

	return result, nil
}

func discoverSpecFiles(specDir string) ([]string, error) {
	entries, err := os.ReadDir(specDir)
	if err != nil {
		return nil, fmt.Errorf("read spec dir: %w", err)
	}

	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := strings.ToLower(entry.Name())
		if !strings.HasSuffix(name, ".yaml") && !strings.HasSuffix(name, ".yml") {
			continue
		}

		files = append(files, filepath.Join(specDir, entry.Name()))
	}

	slices.Sort(files)
	return files, nil
}

func detectVersion(contents []byte) (string, error) {
	text := string(contents)
	switch {
	case strings.Contains(text, "/v1/organizations/"):
		return "v1", nil
	case strings.Contains(text, "/v2/organizations/"):
		return "v2", nil
	default:
		return "", errors.New("could not infer API version from contents")
	}
}

func renderCatalogSource(catalog openapi.Catalog) ([]byte, error) {
	var buffer bytes.Buffer

	buffer.WriteString("// Code generated by openapi-gen; DO NOT EDIT.\n\n")
	buffer.WriteString("package openapi\n\n")
	buffer.WriteString("func generatedCatalog() Catalog {\n")
	buffer.WriteString("\treturn Catalog{\n")
	buffer.WriteString("\t\tVersions: []VersionGroup{\n")
	for _, version := range catalog.Versions {
		writeVersionGroup(&buffer, version, 3)
	}
	buffer.WriteString("\t\t},\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("}\n")

	return buffer.Bytes(), nil
}

func writeVersionGroup(buffer *bytes.Buffer, group openapi.VersionGroup, indent int) {
	writeIndent(buffer, indent)
	buffer.WriteString("{\n")
	writeFieldString(buffer, indent+1, "Name", group.Name)
	writeIndent(buffer, indent+1)
	buffer.WriteString("Tags: []TagGroup{\n")
	for _, tag := range group.Tags {
		writeTagGroup(buffer, tag, indent+2)
	}
	writeIndent(buffer, indent+1)
	buffer.WriteString("},\n")
	writeIndent(buffer, indent)
	buffer.WriteString("},\n")
}

func writeTagGroup(buffer *bytes.Buffer, group openapi.TagGroup, indent int) {
	writeIndent(buffer, indent)
	buffer.WriteString("{\n")
	writeFieldString(buffer, indent+1, "Name", group.Name)
	writeIndent(buffer, indent+1)
	buffer.WriteString("Operations: []Operation{\n")
	for _, operation := range group.Operations {
		writeOperation(buffer, operation, indent+2)
	}
	writeIndent(buffer, indent+1)
	buffer.WriteString("},\n")
	writeIndent(buffer, indent)
	buffer.WriteString("},\n")
}

func writeOperation(buffer *bytes.Buffer, operation openapi.Operation, indent int) {
	writeIndent(buffer, indent)
	buffer.WriteString("{\n")
	writeFieldString(buffer, indent+1, "Version", operation.Version)
	writeFieldString(buffer, indent+1, "Tag", operation.Tag)
	writeFieldString(buffer, indent+1, "CommandName", operation.CommandName)
	writeFieldString(buffer, indent+1, "OperationID", operation.OperationID)
	writeFieldString(buffer, indent+1, "Summary", operation.Summary)
	writeFieldString(buffer, indent+1, "Description", operation.Description)
	writeFieldString(buffer, indent+1, "Method", operation.Method)
	writeFieldString(buffer, indent+1, "Path", operation.Path)
	writeIndent(buffer, indent+1)
	buffer.WriteString("PathParameters: []Parameter{\n")
	for _, parameter := range operation.PathParameters {
		writeParameter(buffer, parameter, indent+2)
	}
	writeIndent(buffer, indent+1)
	buffer.WriteString("},\n")
	writeIndent(buffer, indent+1)
	buffer.WriteString("QueryParameters: []Parameter{\n")
	for _, parameter := range operation.QueryParameters {
		writeParameter(buffer, parameter, indent+2)
	}
	writeIndent(buffer, indent+1)
	buffer.WriteString("},\n")
	writeFieldBool(buffer, indent+1, "HasJSONBody", operation.HasJSONBody)
	writeFieldBool(buffer, indent+1, "BodyRequired", operation.BodyRequired)
	writeFieldString(buffer, indent+1, "BodyDescription", operation.BodyDescription)
	writeIndent(buffer, indent+1)
	buffer.WriteString("Pagination: ")
	buffer.WriteString(paginationConst(operation.Pagination))
	buffer.WriteString(",\n")
	writeIndent(buffer, indent)
	buffer.WriteString("},\n")
}

func writeParameter(buffer *bytes.Buffer, parameter openapi.Parameter, indent int) {
	writeIndent(buffer, indent)
	buffer.WriteString("{\n")
	writeFieldString(buffer, indent+1, "Name", parameter.Name)
	writeFieldString(buffer, indent+1, "FlagName", parameter.FlagName)
	writeFieldString(buffer, indent+1, "In", parameter.In)
	writeFieldString(buffer, indent+1, "Description", parameter.Description)
	writeFieldBool(buffer, indent+1, "Required", parameter.Required)
	writeFieldBool(buffer, indent+1, "Deprecated", parameter.Deprecated)
	writeIndent(buffer, indent+1)
	buffer.WriteString("Type: ")
	buffer.WriteString(paramTypeConst(parameter.Type))
	buffer.WriteString(",\n")
	writeIndent(buffer, indent+1)
	buffer.WriteString("ItemType: ")
	buffer.WriteString(paramTypeConst(parameter.ItemType))
	buffer.WriteString(",\n")
	writeIndent(buffer, indent+1)
	buffer.WriteString("ArrayFormat: ")
	buffer.WriteString(arrayEncodingConst(parameter.ArrayFormat))
	buffer.WriteString(",\n")
	writeIndent(buffer, indent+1)
	buffer.WriteString("Default: ")
	buffer.WriteString(renderAny(parameter.Default))
	buffer.WriteString(",\n")
	writeIndent(buffer, indent+1)
	buffer.WriteString("Enum: ")
	writeStringSlice(buffer, parameter.Enum)
	buffer.WriteString(",\n")
	writeIndent(buffer, indent)
	buffer.WriteString("},\n")
}

func writeFieldString(buffer *bytes.Buffer, indent int, name string, value string) {
	writeIndent(buffer, indent)
	buffer.WriteString(name)
	buffer.WriteString(": ")
	buffer.WriteString(strconv.Quote(value))
	buffer.WriteString(",\n")
}

func writeFieldBool(buffer *bytes.Buffer, indent int, name string, value bool) {
	writeIndent(buffer, indent)
	buffer.WriteString(name)
	buffer.WriteString(": ")
	buffer.WriteString(strconv.FormatBool(value))
	buffer.WriteString(",\n")
}

func writeStringSlice(buffer *bytes.Buffer, values []string) {
	buffer.WriteString("[]string{")
	for index, value := range values {
		if index > 0 {
			buffer.WriteString(", ")
		}
		buffer.WriteString(strconv.Quote(value))
	}
	buffer.WriteString("}")
}

func writeIndent(buffer *bytes.Buffer, indent int) {
	buffer.WriteString(strings.Repeat("\t", indent))
}

func paginationConst(value openapi.PaginationStyle) string {
	switch value {
	case openapi.PaginationV1Page:
		return "PaginationV1Page"
	case openapi.PaginationV1Token:
		return "PaginationV1Token"
	case openapi.PaginationV2Cursor:
		return "PaginationV2Cursor"
	default:
		return "PaginationNone"
	}
}

func paramTypeConst(value openapi.ParamType) string {
	switch value {
	case openapi.ParamInteger:
		return "ParamInteger"
	case openapi.ParamBoolean:
		return "ParamBoolean"
	case openapi.ParamArray:
		return "ParamArray"
	default:
		return "ParamString"
	}
}

func arrayEncodingConst(value openapi.ArrayEncoding) string {
	switch value {
	case openapi.ArrayEncodingCSV:
		return "ArrayEncodingCSV"
	default:
		return "ArrayEncodingRepeat"
	}
}

func renderAny(value any) string {
	switch typed := value.(type) {
	case nil:
		return "nil"
	case string:
		return strconv.Quote(typed)
	case bool:
		return strconv.FormatBool(typed)
	case int:
		return strconv.Itoa(typed)
	case int8:
		return strconv.FormatInt(int64(typed), 10)
	case int16:
		return strconv.FormatInt(int64(typed), 10)
	case int32:
		return strconv.FormatInt(int64(typed), 10)
	case int64:
		return strconv.FormatInt(typed, 10)
	case uint:
		return strconv.FormatUint(uint64(typed), 10)
	case uint8:
		return strconv.FormatUint(uint64(typed), 10)
	case uint16:
		return strconv.FormatUint(uint64(typed), 10)
	case uint32:
		return strconv.FormatUint(uint64(typed), 10)
	case uint64:
		return strconv.FormatUint(typed, 10)
	case float32:
		return strconv.FormatFloat(float64(typed), 'f', -1, 32)
	case float64:
		return strconv.FormatFloat(typed, 'f', -1, 64)
	default:
		return strconv.Quote(fmt.Sprint(value))
	}
}

func exitf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
