# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: upwind

builds:
  - id: upwind
    binary: upwind
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X upwind-cli/internal/buildinfo.Version={{ .Version }}
        -X upwind-cli/internal/buildinfo.Commit={{ .Commit }}
        -X upwind-cli/internal/buildinfo.Date={{ .Date }}

archives:
  - id: upwind-archives
    ids:
      - upwind
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
